name: Issues manager
on: 
  issues:
    types:
      - opened
jobs:
  Validate:
    runs-on: ubuntu-latest
    env:
      ISSUE_CONTEXT: ${{ toJson(github.event.issue) }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: List files in the repository
        uses: actions/checkout@v3.0.2
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.10.7
      - name: Install the dependencies
        run: pip3 install -r requirements.txt
      - name: Process the issues
        run: python3 process_issues.py
