name: Issues manager
on: 
  issues:
    types:
      - opened
jobs:
  Validate:
    runs-on: ubuntu-latest
    env:
      ISSUE_CONTEXT: ${{ toJson(github.event.issue) }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.10.7
      - run: |
          pip3 install -r requirements.txt
          python3 process_issues.py