name: Issues manager
on: 
  issues:
    types:
      - opened
jobs:
  ValidateData:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.10.7
      - uses: jannekem/run-python-script-action@v1.2
        with:
          script: |
            from issues_to_csv import boh
            boh($GITHUB_CONTEXT)
          